# Generated by Django 2.1.7 on 2019-03-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=255)),
                ('audio_features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synaiapp.AudioFeatures')),
            ],
        ),
    ]
