# Generated by Django 2.1.7 on 2019-03-10 15:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0002_analysis'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='analysis',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
