# Generated by Django 2.1.7 on 2019-03-10 18:56

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0003_auto_20190310_1656'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='audiofeatures',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
