# Generated by Django 2.1.7 on 2019-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0004_auto_20190310_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
