# Generated by Django 2.1.7 on 2019-03-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0005_song_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='songs_len',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
