# Generated by Django 2.1.7 on 2019-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0006_analysis_songs_len'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(to='synaiapp.Artist'),
        ),
    ]
