# Generated by Django 2.1.7 on 2019-03-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0007_auto_20190314_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('album_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synaiapp.Album'),
        ),
    ]
