# Generated by Django 2.1.7 on 2019-03-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0008_auto_20190321_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_name',
            new_name='name',
        ),
    ]
