# Generated by Django 2.1.7 on 2019-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0009_auto_20190321_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='datasource_type',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
