# Generated by Django 2.1.7 on 2019-04-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synaiapp', '0010_analysis_datasource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
